---
- name: "create global group"
  group:
    name: "{{ sysops_employer.group }}"
    state: present

- name: "create you personal user"
  user:
    name: "{{ sysops_employer.name }}"
    shell: /bin/bash
    groups: "{{ sysops_employer.group }}"
    password: "{{ sysops_employer.password | password_hash('sha512') }}"
    update_password: always

- name: "enable includedir parameter"
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^includedir /etc/sudoers.d'
    line: 'includedir /etc/sudoers.d'
    validate: /usr/sbin/visudo -cf %s

- name: "add your sudoers-file and check them"
  template:
    src: "sudoers.j2"
    dest: "/etc/sudoers.d/10-admins.conf"
  notify: check sudoers

- name: "add you ssh key to authorized_key"
  authorized_key:
    user: "{{ sysops_employer.name }}"
    key: "{{ sysops_employer.key }}"

- name: "create .bash_profile"
  template:
    src: "bash_profile.j2"
    dest: "/home/{{ sysops_employer.name }}/.bash_profile"
    owner: "{{ sysops_employer.name }}"
    group: "{{ sysops_employer.name }}"
    mode: 0664

- name: "Create .bashrc"
  template:
    src: "bashrc.j2"
    dest: "/home/{{ sysops_employer.name }}/.bashrc"
    owner: "{{ sysops_employer.name }}"
    group: "{{ sysops_employer.name }}"
    mode: 0664

- name: "Install VIM."
  package:
    name: vim
    state: present

- name: "Create .vimrc."
  template:
    src: "vimrc.j2"
    dest: "{{ item }}"
    owner: "{{ sysops_employer.name }}"
    group: "{{ sysops_employer.name }}"
    mode: 0664
  with_items:
    - "/home/{{ sysops_employer.name }}/.vimrc"
    - "/root/.vimrc"
