---
- name: Converge
  hosts: all
  gather_facts: false
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
    - name: Update yum cache.
      apt: update_cache=true
      when: ansible_os_family == 'RedHat'

  roles:
    - role: ../../
