---
name: CI
'on':
  push:
    branches:
      - master
  schedule:
    - cron: "0 4 * * 4"

defaults:
  run:
    working-directory: 'jtprog.my_configuration'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'jtprog.my_configuration'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install test dependencies.
        run: |
          pip3 install --upgrade pip wheel
          pip3 install --upgrade yamllint ansible-lint ansible

      - name: Lint code.
        run: |
          yamllint .
          ansible-lint

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        include:
          - distro: ubuntu2004
            playbook: converge.yml
          - distro: ubuntu1804
            playbook: converge.yml
          - distro: debian10
            playbook: converge.yml
          - distro: debian9
            playbook: converge.yml


    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'jtprog.my_configuration'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install test dependencies.
        run: |
          pip3 install --upgrade pip wheel
          pip3 install --upgrade ansible molecule[docker] docker

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_PLAYBOOK: ${{ matrix.playbook }}
