---
name: Release
'on':
  push:
    tags:
      - '*'

defaults:
  run:
    working-directory: 'jtprog.my_configuration'

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'jtprog.my_configuration'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Ansible.
        run: pip3 install ansible-base

      - name: Trigger a new import on Galaxy.
        run: ansible-galaxy role import --api-key ${{ secrets.ANSIBLE_GALAXY_API_KEY }} $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
